### ISSUE TITLE
Inquiry regarding fan curve functionality

### ISSUE THREAD

**Issue by ghost** [akej74/grid-control#21]
Hi there,

Just a quick question regarding the way the Fan Config tab actually controls the fans. Is the change in fans rpm linear? That is to say, the fans rpm stays flat until the CPU/GPU temps reach the "Start increase fan speed at" value, then it increases at a constant rate until the temps reach the "Intermediate fan speed" value and, finally, it potentially increases at a different constant rate until the temps reach the "Maximum fan speed.

If that is the case, can you give the user more change point? I'm thinking 5-6 points instead of the current 3 (Start, Intermediate, Maximum). This would give the user a more precise control over their fans' rpms.

Thanks!!!

**Comment by akej74** [comment]
Hi, yes, the control is linear and based on the control points as you described (a simple linear equation with different slopes). 

My intention for Grid Control was to have a "real" control curve as in CAM and most other fan control software, allowing for any user customized control curve. The problem here is that the framework I'm using for the user interface (QT) doesn't provide these kind of graphical curve app/widget out of the box. Theoretically, I believe it should be possible to create a custom widget for QT allowing a control curve, but that need a lot of investigation.

I'm note sure about adding more control points, as this will make the UI very cluttered and not so user friendly. A curve widget is the best solution in the long run, I will look into QT a bit more when I get time.

**Comment by ghost** [comment]
Understood. Thanks for considering it
