### ISSUE TITLE
No support for Ryzen 7 CPU

### ISSUE THREAD

**Issue by aebange** [akej74/grid-control#28]
The program does not recognize the thermal sensor data coming from Openhardwaremonitor on my Ryzen 7 1700X. 

OHM: https://i.imgur.com/IriHUdP.png

GC: https://i.imgur.com/uqTWsZi.png

**Comment by akej74** [comment]
Hi, as I don't have this specific HW setup it difficult to troubleshoot the problem. Can you help me by running Grid Control as a Python application and do some debugging...?

**Comment by david-alleyn** [comment]
The solution for this problem is to stop using OpenHardwareMonitor. There is a drop-in replacement for OpenHardwareMonitor called [LibreHardwareMonitor](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor) which is actively maintained. It functions exactly the same and already works with Grid-Control.

In the project's README, there is a link to the latest builds.

**Comment by akej74** [comment]
Thanks @david-alleyn , good point. @aebange please try LibreHardwareMonitor and see if that resolves the issue.

**Comment by aebange** [comment]
@david-alleyn @akej74 Just an update - I have removed OpenHardwareMonitor and replaced it with the forked [LibreHardwareMonitor](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor) that David suggested. LHW works properly  with grid control and does support my CPU. Problem resolved! Thanks guys!

**Comment by akej74** [comment]
Thanks for the update, closing.
